### ISSUE TITLE
Switch demo keys

### ISSUE THREAD

**Issue by thorsten-stripe** [stripe-samples/react-elements-netlify-serverless#2]
@jlengstorf https://react-elements-netlify-serverless.netlify.com/ uses the "Learn with Jason" Stripe test account, can you switch the keys to use the "Netlify Stripe Checkout" test account that https://checkout-netlify-serverless.netlify.app/ uses?

**Comment by jlengstorf** [comment]
just updated these! thanks!

**Comment by thorsten-stripe** [comment]
Thanks, @jlengstorf. Did you update both the publishable and the secret key? When I hit checkout I currently get 
![image](https://user-images.githubusercontent.com/23213994/87210356-d3b26680-c347-11ea-9fa7-62d55ec319cb.png)

**Comment by jlengstorf** [comment]
whoops, fixed now!
