### ISSUE TITLE
Returning error When creating payment intent 

### ISSUE THREAD

**Issue by amirjrn** [stripe-samples/react-elements-netlify-serverless#4]
# Bug report

## Describe the bug
Getting error when runing sample on demo and local . 

## To Reproduce
{"error":{"type":"StripeInvalidRequestError","raw":{"code":"parameter_invalid_integer","doc_url":"https://stripe.com/docs/error-codes/parameter-invalid-integer","message":"Invalid integer: NaN","param":"amount","type":"invalid_request_error","headers":{"server":"nginx","date":"Sun, 17 Jan 2021 12:55:58 GMT","content-type":"application/json","content-length":"240","connection":"keep-alive","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, HEAD, OPTIONS, DELETE","access-control-allow-origin":"*","access-control-expose-headers":"Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required","access-control-max-age":"300","cache-control":"no-cache, no-store","idempotency-key":"stripe-node-retry-857c1ad1-a0d4-4f62-92c9-148a2cc06ad3","original-request":"req_XTlAWwP4B1qSLk","request-id":"req_XTlAWwP4B1qSLk","stripe-version":"2020-03-02","x-stripe-c-cost":"0","strict-transport-security":"max-age=31556926; includeSubDomains; preload"},"statusCode":400,"requestId":"req_XTlAWwP4B1qSLk"},"rawType":"invalid_request_error","code":"parameter_invalid_integer","doc_url":"https://stripe.com/docs/error-codes/parameter-invalid-integer","param":"amount","headers":{"server":"nginx","date":"Sun, 17 Jan 2021 12:55:58 GMT","content-type":"application/json","content-length":"240","connection":"keep-alive","access-control-allow-credentials":"true","access-control-allow-methods":"GET, POST, HEAD, OPTIONS, DELETE","access-control-allow-origin":"*","access-control-expose-headers":"Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required","access-control-max-age":"300","cache-control":"no-cache, no-store","idempotency-key":"stripe-node-retry-857c1ad1-a0d4-4f62-92c9-148a2cc06ad3","original-request":"req_XTlAWwP4B1qSLk","request-id":"req_XTlAWwP4B1qSLk","stripe-version":"2020-03-02","x-stripe-c-cost":"0","strict-transport-security":"max-age=31556926; includeSubDomains; preload"},"requestId":"req_XTlAWwP4B1qSLk","statusCode":400}}
Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
The amount passed was NaN. 

amount: "NaN", 

Can you review the call to create the payment intent and ensure a valid amount was passed?
